### ISSUE TITLE
zef install shows test failure

### ISSUE THREAD

**Issue by tbrowder** [gfldex/perl6-typesafe-xhtml-writer#1]
$ zef install --force Typesafe::XHTML::Writer
===> Searching for: Typesafe::XHTML::Writer
===> Searching for missing dependencies: Typesafe::HTML
===> Building: Typesafe::XHTML::Writer:ver('0.1.0')
===> Building [OK] for Typesafe::XHTML::Writer:ver('0.1.0')
===> Testing: Typesafe::HTML:ver('0.1.0')
===> Testing [OK] for Typesafe::HTML:ver('0.1.0')
===> Testing: Typesafe::XHTML::Writer:ver('0.1.0')
Parameter '$e' expected a writable container, but got Str value
  in sub td at /home/tbrowde/.zef/store/perl6-typesafe-xhtml-writer.git/7253521690f26efa94c6d3625ac6c4f28052488c/lib/Typesafe/XHTML/Writer.pm6 (Typesafe::XHTML::Writer) line 2428
  in block <unit> at t/basic.t line 22

Parameter '$e' expected a writable container, but got Str value
  in sub td at /home/tbrowde/.zef/store/perl6-typesafe-xhtml-writer.git/7253521690f26efa94c6d3625ac6c4f28052488c/lib/Typesafe/XHTML/Writer.pm6 (Typesafe::XHTML::Writer) line 2428
  in block <unit> at t/no-indent.t line 24

Parameter '$e' expected a writable container, but got Str value
  in sub span at /home/tbrowde/.zef/store/perl6-typesafe-xhtml-writer.git/7253521690f26efa94c6d3625ac6c4f28052488c/lib/Typesafe/XHTML/Writer.pm6 (Typesafe::XHTML::Writer) line 919
  in block <unit> at t/parametric.t line 23

Parameter '$e' expected a writable container, but got Str value
  in sub xhtml-skeleton at /home/tbrowde/.zef/store/perl6-typesafe-xhtml-writer.git/7253521690f26efa94c6d3625ac6c4f28052488c/lib/Typesafe/XHTML/Skeleton.pm6 (Typesafe::XHTML::Skeleton) line 5
  in block <unit> at t/skeleton.t line 27

===> Testing [FAIL]: Typesafe::XHTML::Writer:ver('0.1.0')
===> Installing: Typesafe::HTML:ver('0.1.0')
===> Installing: Typesafe::XHTML::Writer:ver('0.1.0')

**Comment by tbrowder** [comment]
Investigating...

**Comment by gfldex** [comment]
fixed with 5c1fad25759378d43536ea14312da6d017d4af85
